### ISSUE TITLE
is unwrap() normal/necessary?

### ISSUE THREAD

**Issue by aaronpeacock** [Daiki48/axum-tera#1]
I see this pattern a lot in the examples and docs:
```
 let output = TEMPLATES.render("page.tera", &context);
 Html(output.unwrap() )
```

I wonder about unwrap() and production usage of Tera with Axum.
Doesn't unwrap() panic? 
What's the safe way to use Tera rendering in Axum?

**Comment by Daiki48** [comment]
Hi @aaronpeacock 
This repository is the code I tried at the time.
And I did not write error handling at that time.
Because this code is for trying. haha

```
mismatched types
expected struct `std::string::String`
     found enum `std::result::Result<std::string::String, tera::Error>`

Related information:

  * main.rs#38,5: arguments to this struct are incorrect
  * main.rs#38,5: the type constructed contains `std::result::Result<std::string::String, tera::Error>` due to the type of the argument passed
  * mod.rs#43,12: tuple struct defined here
  * main.rs#38,16: consider using `Result::expect` to unwrap the `std::result::Result<std::string::String, tera::Error>` value, panicking if the value is a `Result::Err`: `.expect("REASON")`

 (rustc E0308)
```

However, thanks to you I was able to review this code.
I'll try to fix it now.

**Comment by Daiki48** [comment]
I believe this code has answered your question.
If you have another question, please create an Issue.
Thank you :+1:
